### ISSUE TITLE
Periodic Boundary Conditions per Direction

### ISSUE THREAD

**Issue by ranocha** [IANW-Projects/ConservationLaws#30]
Up to now, we only have the possibility to use periodic boundaries everywhere or nowhere. For many tests cases such as 2D Alfvén waves, having the possibility to use periodic boundaries in z direction and other boundaries for x and y can be really helpful.

**Comment by simonius** [comment]
I would like to work on this issue. My plan would be to exchange USE_PERIODIC with USE_PERIODIC_X, USE_PERIODIC_Y and USE_PERIODIC_Z.  What is your opinion ?

**Comment by ranocha** [comment]
That's great, thanks a lot! I would have chosen the same approach.

These changes might be a bit involved because you have to fiddle with the index operations in utils.h (which should be possible; you can move the `#ifdef`s inside the functions) and some optimisations done for periodic boundaries in the other files in include/. If I were you, I would just ignore these optimisations at the beginning and create a working version. Whether/how optimisations can be added is a good second step.

**Comment by ranocha** [comment]
Closed in #37.
